### ISSUE TITLE
Files with data descriptor record are not supported

### ISSUE THREAD

**Issue by pierre-pretorius** [ananthakumaran/zstream#20]
I create a zip file exactly like in the example:
```
Zstream.zip([Zstream.entry("some.pdf", File.stream!("some.pdf", [], 512), coder: Zstream.Coder.Deflate)])
  |> Stream.into(File.stream!("archive.zip"))
  |> Stream.run()
```
The archive.zip file can be opened and extracted by the Ubuntu Archive Manager.

I then read the zip as shown in the example:
```
    File.stream!("archive.zip", [], 512)
    |> Zstream.unzip()
    |> Enum.reduce(%{}, fn
      {:entry, %Zstream.Entry{name: file_name} = entry}, state -> state
      {:data, :eof}, state -> state
      {:data, data}, state -> state
    end)
```

It gives this error:
```
** (Zstream.Unzip.Error) Zip files with data descriptor record are not supported
    (zstream 0.6.4) lib/zstream/unzip.ex:140: Zstream.Unzip.local_file_header/2
```

If I debug, this is what the local header looks like:
```
%Zstream.Unzip.LocalHeader{
  compressed_size: 0,
  compression_method: 8,
  crc32: 0,
  extra_field: nil,
  extra_field_length: 0,
  extras: nil,
  file_name: nil,
  file_name_length: 8,
  general_purpose_bit_flag: 2056,
  last_modified_file_date: 22180,
  last_modified_file_time: 1304,
  uncompressed_size: 0,
  version_need_to_extract: 20
}
```

If I use the Ubuntu Archive Manager to create a zip file of the exact same PDF, then Zstream is able to read that zip file.  The problem only occurs with zip files created by Zstream.  Since it's the most basic example, I guess it's an OTP or Elixir version problem?

**Comment by ananthakumaran** [comment]
This is a fundamental issue with how Zip file format is designed. This library, as the name implies, works on stream which is not rewindable. But to properly parse Zip file with data descriptor, the parser needs to go back, which is not possible with stream abstraction. More info can be found under [notes](https://hexdocs.pm/zstream/Zstream.html#unzip/1-notes).

If the file size is not big, you can use Erlang zip or you can checkout https://github.com/akash-akya/unzip.
