### ISSUE TITLE
Special character strings

### ISSUE THREAD

**Issue by saitama-the-coder** [ananthakumaran/zstream#4]
Hi.

I tried to compress a file using the lib, it was a success but the file name does not remain the same, as if an encoding error had occurred.

Here is the code:
```elixir
[Zstream.entry(file_name_with_extension, File.stream!(file_path, [:utf8]))]
|> Zstream.zip()
|> Stream.into(File.stream!(file_path_zip))
|> Stream.run()
```

The "file_name_with_extension" value is "Relatório.csv", but when the file is built the name inside the zip is "Relat├│rio.csv".

**Comment by ananthakumaran** [comment]
Could you share more info about the client used to unzip the files. Some clients do have issues with unicode characters. It's also possible the bug is in zstream, but want to confirm if the client is capable of handling unicode file names.

**Comment by saitama-the-coder** [comment]
I'm using the ubuntu default unzip lib, i believe the name is simply "zip".

**Comment by ananthakumaran** [comment]
I faced similar issue with macox `unzip`. Some of the older clients don't handle utf chars. But I could unzip properly with unarchiver. You could try other clients or check https://gildas-lormeau.github.io/zip.js/demos/demo2.html

**Comment by saitama-the-coder** [comment]
Thank you! That worked for me.
