### ISSUE TITLE
Zip not fully formed

### ISSUE THREAD

**Issue by Lazarus404** [ananthakumaran/zstream#5]
I'm using your library to stream files from a Phoenix endpoint.  The endpoint looks something like this:

    def download_file_list(conn, paths, uri, basepath) do
      conn =
        conn
        |> put_resp_content_type(Plug.MIME.type("zip"))
        |> put_resp_header(
          "content-disposition",
          "attachment; filename=\"#{Path.basename(basepath)}.zip\""
        )
        |> send_chunked(200)

      Enum.map(paths, fn path ->
        path_size = byte_size(uri)

        rel_path =
          case String.starts_with?(path, uri) do
            true ->
              <<_::binary-size(path_size), trailing::binary()>> = path
              trailing

            _ ->
              path
          end

        stream = File.stream!(path, [], @chunk_size)
        Zstream.entry(rel_path, stream, coder: Zstream.Coder.Stored)
      end)
      |> Zstream.zip()
      |> Enum.reduce_while(conn, fn chunk, conn ->
        case Plug.Conn.chunk(conn, chunk) do
          {:ok, conn} ->
            {:cont, conn}

          {:error, :closed} ->
            {:halt, conn}
        end
      end)
    end

However, when downloading the zip, while it opens fine on Linux or with WinZip etc., it fails to open with Windows or Macs native archive tools.

Is this something that is known?  Am I missing something?  I can upload a zip somewhere if that will help.

**Comment by ananthakumaran** [comment]
Could you try to run `zipinfo -v filename.zip`, if it doesn't report any error, then the file is encoded correctly. Zstream makes use of a feature called [data descriptor](https://en.wikipedia.org/wiki/Zip_(file_format)#Data_descriptor), which allows us to stream data without knowing the file size beforehand. Some older versions of zip tools might not handle it correctly.

**Comment by Lazarus404** [comment]
The data reported by `zipinfo` is:

Archive:  06. EPC.zip
    The zipfile comment is 18 bytes long and contains the following text:
    ======================== zipfile comment begins ==========================
    Created by Zstream
    ========================= zipfile comment ends ===========================

    End-of-central-directory record:
    -------------------------------

      Zip archive file size:                    429448 (0000000000068D88h)
      Actual end-cent-dir record offset:        429408 (0000000000068D60h)
      Expected end-cent-dir record offset:      429408 (0000000000068D60h)
      (based on the length of the central directory and its expected offset)

      This zipfile constitutes the sole disk of a single-part archive; its
      central directory contains 4 entries.
      The central directory is 346 (000000000000015Ah) bytes long,
      and its (expected) offset in bytes from the beginning of the zipfile
      is 429062 (0000000000068C06h).


    Central directory entry #1:
    ---------------------------

      /epc wd2 rr_0196-2227-9940-9400-7813.pdf

      offset of local header from start of archive:   329674
                                                      (00000000000507CAh) bytes
      file system or operating system of origin:      MS-DOS, OS/2 or NT FAT
      version of encoding software:                   5.2
      minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
      minimum software version required to extract:   2.0
      compression method:                             none (stored)
      file security status:                           not encrypted
      extended local header:                          yes
      file last modified on (DOS date/time):          2020 Feb 29 08:31:44
      32-bit CRC value (hex):                         d9bde4c5
      compressed size:                                99302 bytes
      uncompressed size:                              99302 bytes
      length of filename:                             40 characters
      length of extra field:                          0 bytes
      length of file comment:                         0 characters
      disk number on which file begins:               disk 1
      apparent file type:                             binary
      non-MSDOS external file attributes:             81A400 hex
      MS-DOS file attributes (00 hex):                none

      There is no file comment.

    Central directory entry #2:
    ---------------------------

      There are an extra -215473 bytes preceding this file.

      /epc wd1 epc_0930-0138-0409-4222-1006.pdf

      offset of local header from start of archive:   213573
                                                      (0000000000034245h) bytes
      file system or operating system of origin:      MS-DOS, OS/2 or NT FAT
      version of encoding software:                   5.2
      minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
      minimum software version required to extract:   2.0
      compression method:                             none (stored)
      file security status:                           not encrypted
      extended local header:                          yes
      file last modified on (DOS date/time):          2020 Feb 29 08:31:44
      32-bit CRC value (hex):                         387ce4b3
      compressed size:                                116014 bytes
      uncompressed size:                              116014 bytes
      length of filename:                             41 characters
      length of extra field:                          0 bytes
      length of file comment:                         0 characters
      disk number on which file begins:               disk 1
      apparent file type:                             binary
      non-MSDOS external file attributes:             81A400 hex
      MS-DOS file attributes (00 hex):                none

      There is no file comment.

    Central directory entry #3:
    ---------------------------

      There are an extra -230774 bytes preceding this file.

      /epc wd2 epc_0971-0238-7499-6922-1002.pdf

      offset of local header from start of archive:   98884
                                                      (0000000000018244h) bytes
      file system or operating system of origin:      MS-DOS, OS/2 or NT FAT
      version of encoding software:                   5.2
      minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
      minimum software version required to extract:   2.0
      compression method:                             none (stored)
      file security status:                           not encrypted
      extended local header:                          yes
      file last modified on (DOS date/time):          2020 Feb 29 08:31:44
      32-bit CRC value (hex):                         506c60d7
      compressed size:                                114602 bytes
      uncompressed size:                              114602 bytes
      length of filename:                             41 characters
      length of extra field:                          0 bytes
      length of file comment:                         0 characters
      disk number on which file begins:               disk 1
      apparent file type:                             binary
      non-MSDOS external file attributes:             81A400 hex
      MS-DOS file attributes (00 hex):                none

      There is no file comment.

    Central directory entry #4:
    ---------------------------

      There are an extra -213557 bytes preceding this file.

      /epc wd1 rr_0220-3941-0408-0920-1040.pdf

      offset of local header from start of archive:   0
                                                      (0000000000000000h) bytes
      file system or operating system of origin:      MS-DOS, OS/2 or NT FAT
      version of encoding software:                   5.2
      minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
      minimum software version required to extract:   2.0
      compression method:                             none (stored)
      file security status:                           not encrypted
      extended local header:                          yes
      file last modified on (DOS date/time):          2020 Feb 29 08:31:44
      32-bit CRC value (hex):                         efe42b42
      compressed size:                                98798 bytes
      uncompressed size:                              98798 bytes
      length of filename:                             40 characters
      length of extra field:                          0 bytes
      length of file comment:                         0 characters
      disk number on which file begins:               disk 1
      apparent file type:                             binary
      non-MSDOS external file attributes:             81A400 hex
      MS-DOS file attributes (00 hex):                none

      There is no file comment.

**Comment by ananthakumaran** [comment]
I don't see anything wrong here. I run the test suite locally on mac and don't get any failures with unzip. Could you share the errors you get in mac and windows?

**Comment by Lazarus404** [comment]
Hi ananthakumaran,

I sent a zip file to you, but not sure if it reached you, as I don't see the message here.  Is there any way I can get it to you?

**Comment by Lazarus404** [comment]
I added you to a repo containing the zip file.  I figured it was the simplest option.

https://github.com/Lazarus404/faulty-zip

**Comment by ananthakumaran** [comment]
```

**Comment by ananthakumaran** [comment]
```
zipinfo epc.zip
Archive:  epc.zip
Zip file size: 429448 bytes, number of entries: 4
-rw-r--r--  5.2 fat    99302 bl stor 20-Feb-29 08:31 /epc wd2 rr_0196-2227-9940-9400-7813.pdf
-rw-r--r--  5.2 fat   116014 bl stor 20-Feb-29 08:31 /epc wd1 epc_0930-0138-0409-4222-1006.pdf
-rw-r--r--  5.2 fat   114602 bl stor 20-Feb-29 08:31 /epc wd2 epc_0971-0238-7499-6922-1002.pdf
-rw-r--r--  5.2 fat    98798 bl stor 20-Feb-29 08:31 /epc wd1 rr_0220-3941-0408-0920-1040.pdf
4 files, 428716 bytes uncompressed, 428716 bytes compressed:  0.0%
~/Downloads|⇒ unzip epc.zip
Archive:  epc.zip
Created by Zstream
warning:  stripped absolute path spec from /epc wd2 rr_0196-2227-9940-9400-7813.pdf
 extracting: epc wd2 rr_0196-2227-9940-9400-7813.pdf
warning:  stripped absolute path spec from /epc wd1 epc_0930-0138-0409-4222-1006.pdf
 extracting: epc wd1 epc_0930-0138-0409-4222-1006.pdf
warning:  stripped absolute path spec from /epc wd2 epc_0971-0238-7499-6922-1002.pdf
 extracting: epc wd2 epc_0971-0238-7499-6922-1002.pdf
warning:  stripped absolute path spec from /epc wd1 rr_0220-3941-0408-0920-1040.pdf
 extracting: epc wd1 rr_0220-3941-0408-0920-1040.pdf
```

The files are added with absolute path (with `/` in the front), could you try to remove that and use relative path? I am not still sure if this is the only problem

**Comment by Lazarus404** [comment]
Of course. I will try that shortly.

**Comment by Lazarus404** [comment]
Okay, that seems to have worked.  I will be asking the person who raised the issue to test some more, but it looks fine to me, now.  Thanks for looking into this.

**Comment by Lazarus404** [comment]
Okay, so, it opens in Windows, now, but Mac's give the error 
"Unable to expand "archive.zip" into "Downloads". (Error 2 - No such file or directory.)"

**Comment by ananthakumaran** [comment]
Could you upload the new file to the repo

**Comment by Lazarus404** [comment]
Done

**Comment by ananthakumaran** [comment]
Could you try this branch https://github.com/ananthakumaran/zstream/pull/6 and see if it solves the issue. I don't know the exact reason why mac os x archiver fails, but if I keep the order same, it seems to work (at least for the file you shared).

**Comment by Lazarus404** [comment]
Trying now

**Comment by Lazarus404** [comment]
That worked for Mac, thank you.
